language: rust
os: linux
dist: xenial
install: skip
script:
- echo "script!"
deploy:
  provider: cargo
  edge: true
  token:
    secure: ubET8NvRqE/l41x1PvK0kLmtPeylZJHgyJvB7Wk22TgvIwEnBaPqTtRsu6AMb3dX/LGWfCKh3+gHMKE/omYwwT3jQsMG96daLGGT+dfcxpNtfkzIfFwyRsgsQPAxLlMZcbcuzp4rTD3cF1fjxNv7I5trTRI/5v30dy1JAkQuuJGoPRfPqL56lO/qPqhXG79jTIf4IAozkKbJCgBzeU/4cZBDTfKaIjhN5GJrAjTPQhk8nqS9mha/1p7QRYs1p+pKbr4gK1SBkdz6ikiJYgKbTGzJjp6yt/p2V3c4VW+HNBidHSHa7AbkwF03icR8TGjRwTzyCTCU+h3N/62ZreXmJez7LVMrIt+kNtT2bSj6ehlU1VdcjzcoBa7LJZR9DHa3XG6fu325ULBiD3DjxBSTPwcM5xAPoK2RZe54p7MrM+wniNj2RHjnVk+UFlcATGmjhzLUutKvWID1xp9cciQ96wxJjMf6QrsnfWQbh3m8Wmianjd6aW2LY8YDvHAJqbu0bor0QvO0Cgrr2bYASXEBxG8Hm67UzSSgoeYolkJZoxfb+bkjrucmSVYYo62+oubVrjunHo/+mdY1v2/DZrrP2w2Dub9nqjJOSxhaUd5rzXRHc+NN8FgYx7lW2lkfZ8/3Nm9iNPLMNac4iNdm6C2lMnrcXSGWUiLYnX1RzgC+C6Q=
  on:
    tags: true
    branch: master
