language: rust
os: linux
dist: xenial
install: skip
script:
  - echo "script!"
deploy:
  provider: cargo
  token:
    secure: diSsmuZbF9y5o020zMQouMgZG1xj48/Cq424pZe101EFI6jlaeVG5v8MCl70WEG+33AhSaDWG11Ff2O0mWLUhe9M65Kag7ivbfAJ6aQu8dFv3PshAQTxY/Q21jerAdtHUccnuvPMPzIklK6UMmYeXNF1BYIFPNfDUX6o56vva22xRl4AxjyRyD1NNk3h+zP8szxd7PCaq6myzd8cUk9GcEWuUPhDqAPBM9vSprHNfVhbgUC6uafHQUmA97SX13vN7wqC93MSeUj8kZiM0erksOZwOtR7DrUQDGDd7jGXO4C5OcnSMjSiXoxPFvINbKJId09Sal6bzrnmaspICpNpROgWhv0AQ43pG1bAH9Rp8Eq1TtBHI+f369bS7ab4/AcMjuLv/MOgvtrwcGwkDNQVK5k3jeafDyH/7+fXuLPYAVWbL727jtXp8jJEed8zh6xazjOr7r8j4N7UWv0DQuEqMXUo+TbT2l4dztY5fdcZoesZ7zUxvj2yuwdfaFJbycDA3e6GcyT8zusNVmbKqmc0B/pvQUt7CBeYIlNsXzdMG78peG+PwUTTAnRKe9pqtstBPORRZVo/BZ6kl8EPNi10g4h7yF90YHxfhhrvgMHPzB0zqv3znDXf0Tgfv6zrhEECon3qi1Qe3T4LN/YFBYaYsLe/XIvrrqqNOCtStnycduU=
  on:
    tags: true
    branch: master
