language: rust
os: linux
dist: xenial

install: skip

script:
  - cargo build --release

deploy:
  provider: cargo
  token: wAGXp2ripqxqRtdjoydc6hSwRfBkhoowB3jIv/5S3NDvQ3eGOQCZEArVjfJoqR1pG+AeXX92gEC4Q3CSIqWK6MnvURWw7TMdhhTjiNRux9rD/IOPdaG/vlGUlb0GYSAozTnaHIbInQdoT4Mk8Oj6ydjL5buU3DK1DTn1hezqP68VOuBe5y0YzWwaLFOeBp3vNhQO/DlaiJALXkslZSi43JMBLIQUeFTmSO66RWs0fXAF6NTc4rx32vcQoAwyt6ccXVUsgwG663Jn0QOdub/xPNLLBe9qXRDKqLTMH+HxtHlYyTFzoVgPPdTHyDJF0cSKYruFiiySiiUYEIDFKk7EMUliYHMx0FiNnH7tOlGHlNafpTGEm24dfoF8OULJ+DaEdCeiJmpj13oaiy81TIpwyPRh3B7c9gtiak3Fvjb0G4JSHZy+AdaiOzET4BB8YBqZvL5zizW/q3+QwlYGVLRwIVfh07ZUTVz5u/lkJh2HOVgHWFb+OSctBpBw8E1/nwF3TEeIRrEx47fqd+ftviue5Tbr2+cUvqQ3ygtfUFluji38JfGv97zhVNJ9N28jT29zTGkvV1TiX76q+Njg7rM1E2HYFQCBfTenzEfwxoaGB5KZQFNCShsZhlERYsDfV77tk41JYCJXZmgkrFQqIEnRT4K1cY6m7tiQqpqEnUojjVI=
  on:
    tags: true
    branch: master
