[package]
name = "heliocron"
version = "0.1.3"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
structopt = "0.3"

[dev-dependencies]
criterion = "0.3"

[profile.release]
lto = true

[[bench]]
name = "benches"
harness = false
